### ISSUE TITLE
Single annotation is also shown as FBAnnotationCluster & Map is full zoomed in to current location

### ISSUE THREAD

**Issue by sakshiGoel26** [ribl/FBAnnotationClusteringSwift#4]
1. On adding annotations on mapview, sometimes single annotation is also added as FBAnnotationCluster.
2. Also on full zoom in mode cluster splits into single annotation & map is full zoomed to current location, if i changed value of scale to 1.5 in order to reduce zoom in region then it affects clustering.

Please help me out in resolving these two issues.

**Comment by chenr2** [comment]
Thanks for finding these bugs.  I'll look into these and let you know what I find.

**Comment by chenr2** [comment]
I'm having trouble reproducing this, or even visualizing the problem.  Is there a sample project that demonstrates the issue, screenshots, and specific steps to reproduce the issues?  Thanks!

**Comment by sakshiGoel26** [comment]
Thank you for your response. 

Suppose if i have list of coordinates like 
(   "Latitude":"28.615614","Longitude":"77.374428",), ("Latitude":"28.615606", "Longitude":"77.374435",), ( "Latitude":"28.615612","Longitude":"77.374428"),("Latitude":"28.535515","Longitude":"77.391022"),("Latitude":"28.615604", "Longitude":"77.374435"), ( "Latitude":"28.615608","Longitude":"77.374428"), ( "Latitude":"28.615606","Longitude":"77.374435"),(  "Latitude":"28.615595","Longitude":"77.374405"), ( "Latitude":"28.615616","Longitude":"77.374428")

then on adding cluster for these annotations, sometimes it add coordinate   "Latitude":"28.535515",  "Longitude":"77.391022") annotation as cluster and sometimes as single annotation on coming back & forth from this map view.

Can you check the problem using these coordinates? It will be really helpful.

**Comment by chenr2** [comment]
After playing around with these coordinates, it seems like the pin outlier (on Dadri Road) may or may not be included in the cluster depending on the zoom level.  

<img width="171" alt="screen shot 2015-11-02 at 9 31 22 am" src="https://cloud.githubusercontent.com/assets/10889121/10885236/4598c130-814a-11e5-864c-97e18f5cda8e.png">

<img width="195" alt="screen shot 2015-11-02 at 9 31 30 am" src="https://cloud.githubusercontent.com/assets/10889121/10885238/49bd5884-814a-11e5-970c-728f54afe271.png">

I think the algorithm recursively divides the screen into quarters to determine which pins get clustered together:

https://images.thoughtbot.com/ios-maps-blog-post-images/quadTreeInsert.gif

Notice how all the boxes are very tall, due to the portrait screen size.  In the coordinates you provided, the Dadri Road pin would fit inside a "tall box" and get included in the cluster despite being far away (depending on the zoom level).  

I think this is just how the algorithm works though -- by optimizing on speed rather than relative pin distances.  

<img width="322" alt="screen shot 2015-11-02 at 9 42 37 am" src="https://cloud.githubusercontent.com/assets/10889121/10885254/63bb9aa2-814a-11e5-82c5-728069bd323f.png">

<img width="370" alt="screen shot 2015-11-02 at 9 52 07 am" src="https://cloud.githubusercontent.com/assets/10889121/10885258/677e245c-814a-11e5-984f-f62b5510a28b.png">

**Comment by sakshiGoel26** [comment]
Thank you so much , really appreciate your effort. Can you please tell how you are handling zoom in level of map in this,as asked in my first question, 2nd point?

I am not setting region of map anywhere in my code, but on zooming out I am hitting service if new center of map is out of say 1000 radius from previous center, in this case map is automatically zoomed in to those new annotations. How can i prevent this zoom in functionality on adding annotation without affecting clustering?

**Comment by chenr2** [comment]
I don't think the library zooms or pans the map by itself.  `clusteringManager.clusteredAnnotationsWithinMapRect` does ask for the zoom scale, but that's just to figure out which annotations to render on the screen.

In the sample project, the map is panned to coordinates (0, 0) by setting `mapView.centerCoordinate`.  In another project, I use `mapView.setRegion` to zoom in on a particular coordinate.  But this is outside of the library's code.

My first instinct would be to search the project for `setRegion`, and keep an eye out in the callback that gets executed after getting data from the service.

**Comment by sakshiGoel26** [comment]
Thank you my issue was resolved, I have added showAnnotation in my code that's why it was zoomed in so much.
